# -*- coding: utf-8 -*-
"""Modelo ML Fase4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyiIaNG6Ic5lJOyHQNOSHvlNPvWEbYic
"""

# ==============================================================================
# ARQUIVO: app.py (Deploy do Sistema Preditivo com Streamlit)
# ==============================================================================
import streamlit as st
import pandas as pd
import numpy as np
import pickle

# 1. Configuração da página do Streamlit
st.set_page_config(
    page_title="Predição de Obesidade - Hospital",
    page_icon="🩺",
    layout="centered"
)

# 2. Função para carregar os artefatos salvos
@st.cache_resource
def carregar_modelo():
    with open('modelo_obesidade_xgb.pkl', 'rb') as f_modelo:
        modelo = pickle.load(f_modelo)
    with open('label_encoder.pkl', 'rb') as f_encoder:
        encoder = pickle.load(f_encoder)
    return modelo, encoder

try:
    modelo_campeao, label_encoder = carregar_modelo()
except FileNotFoundError:
    st.error("Erro: Arquivos 'modelo_obesidade_xgb.pkl' ou 'label_encoder.pkl' não foram encontrados no diretório.")
    st.stop()

# 3. Interface Visual (Visão de Negócio / Médica)
st.title("🩺 Sistema de Suporte ao Diagnóstico de Obesidade")
st.markdown("""
Esta plataforma auxilia a equipe médica na triagem e identificação do nível de obesidade e sobrepeso de pacientes,
utilizando um modelo preditivo baseado em inteligência artificial (XGBoost) com **95.98% de acurácia**.
""")
st.hr()

st.subheader("📋 Formulário de Triagem do Paciente")

# Criando duas colunas para organizar o formulário médico
col1, col2 = st.columns(2)

with col1:
    genero = st.selectbox("Gênero do Paciente:", ["Feminino", "Masculino"])
    idade = st.number_input("Idade (anos):", min_value=1, max_value=120, value=25)
    altura = st.number_input("Altura (metros):", min_value=0.50, max_value=2.50, value=1.70, step=0.01)
    peso = st.number_input("Peso (kg):", min_value=1.0, max_value=300.0, value=70.0, step=0.1)
    historico_familiar = st.selectbox("Histórico Familiar de Sobrepeso?", ["Sim", "Não"])
    alimentos_caloricos = st.selectbox("Consome alimentos altamente calóricos com frequência?", ["Sim", "Não"])
    consumo_vegetais = st.slider("Frequência de consumo de vegetais (1 a 3):", 1.0, 3.0, 2.0, step=0.5)
    refeicoes_principais = st.slider("Número de refeições principais por dia:", 1.0, 4.0, 3.0, step=1.0)

with col2:
    entre_refeicoes = st.selectbox("Consome alimentos entre as refeições?", ["Nunca", "Às vezes", "Frequentemente", "Sempre"])
    fumante = st.selectbox("O paciente é fumante?", ["Sim", "Não"])
    consumo_agua = st.slider("Consumo diário de água (Aprox. em Litros):", 1.0, 3.0, 2.0, step=0.5)
    monitora_calorias = st.selectbox("Monitora as calorias diárias ingeridas?", ["Sim", "Não"])
    atividade_fisica = st.slider("Frequência de atividade física (0 a 3):", 0.0, 3.0, 1.0, step=0.5)
    uso_tecnologia = st.slider("Tempo de uso de dispositivos tecnológicos (0 a 2):", 0.0, 2.0, 1.0, step=0.5)
    consumo_alcool = st.selectbox("Frequência de consumo de álcool?", ["Nunca", "Às vezes", "Frequentemente", "Sempre"])
    meio_transporte = st.selectbox("Meio de transporte principal utilizado:",
                                   ["Transporte Público", "Automóvel", "Andando", "Motocicleta", "Bicicleta"])

st.hr()

# 4. Processamento da Predição
if st.button("🔮 Executar Diagnóstico Preditivo", type="primary"):

    # Criando o DataFrame exatamente com a estrutura esperada pelo Pipeline do Cenário 1
    dados_paciente = pd.DataFrame([{
        'genero': genero,
        'idade': idade,
        'altura': altura,
        'peso': peso,
        'historico_familiar_sobrepeso': historico_familiar,
        'consome_alimentos_alto_calorico': alimentos_caloricos,
        'frequencia_consumo_vegetais': consumo_vegetais,
        'numero_refeicoes_principais': refeicoes_principais,
        'consome_entre_refeicoes': entre_refeicoes,
        'fumante': fumante,
        'consumo_agua_diario': consumo_agua,
        'monitora_calorias_diarias': monitora_calorias,
        'frequencia_atividade_fisica': atividade_fisica,
        'tempo_dispositivos_tecnologicos': uso_tecnologia,
        'frequencia_consumo_alcool': consumo_alcool,
        'meio_transporte': meio_transporte
    }])

    # Executando a predição através do Pipeline (ele faz todo o Feature Engineering automaticamente)
    predicao_codificada = modelo_campeao.predict(dados_paciente)

    # Decodificando o rótulo numérico de volta para o texto médico original
    resultado_final = label_encoder.inverse_transform(predicao_codificada)[0]

    # Exibindo o resultado em um box estilizado de sucesso
    st.success(f"### 📋 Diagnóstico Estimado: **{resultado_final}**")
    st.info("Nota: Este sistema serve como ferramenta de triagem baseada em dados estatísticos e não substitui a avaliação soberana do médico especialista.")
